/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: SENSOR PIANO
// PLATFORM:     HT-PICC 14-bit
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS               3  // Number of tasks that can be active at one time
#define OS_DISABLE_PRIORITY        // 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS
#define OS_USE_INLINE_TIMER        // Make OS_Timer service as in-line function




//------------------------------------------------------------------------------
// BANKS
//------------------------------------------------------------------------------

#define OS_BANK_OS             2  // RAM bank to allocate all system variables


//------------------------------------------------------------------------------
// TYPES
//------------------------------------------------------------------------------

#define OS_TTIMER_SIZE         1


#endif

